Repository seoul-night/ddubam-client, pull requests merged in 2024-06, with the labels that each got.

#6 fix: 완료 후기 리스트
  src/components/FinishedTab.jsx
  src/pages/FinishedPath.jsx
  src/services/api.js
Labels: fix, 🟡 보통

#8 Feat/4 api header
  src/pages/Home.jsx
  src/pages/Loading.jsx
  src/pages/Onboarding.jsx
  src/pages/PathDetail.jsx
  src/pages/Walking.jsx
  src/services/api.js
  src/utils/api-utils.js
  src/utils/http-commons.js
Labels: feat, 🟠 높음

#11 Fix/10 search page fix
  src/components/ReviewModal.jsx
  src/pages/Home.jsx
  src/pages/Navigation.jsx
  src/pages/Search.jsx
  src/pages/Searching.jsx
  src/services/api.js
Labels: fix, 🟠 높음

#15 Fix/14 design
  src/pages/Navigation.jsx
  src/pages/Search.jsx
Labels: fix
